[2025-07-07T00:00:12.938+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: soda_scan_example.run_soda_scan scheduled__2025-07-06T00:00:00+00:00 [queued]>
[2025-07-07T00:00:12.949+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: soda_scan_example.run_soda_scan scheduled__2025-07-06T00:00:00+00:00 [queued]>
[2025-07-07T00:00:12.950+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-07-07T00:00:12.959+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): run_soda_scan> on 2025-07-06 00:00:00+00:00
[2025-07-07T00:00:12.969+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'soda_scan_example', 'run_soda_scan', 'scheduled__2025-07-06T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/soda_scan_dag.py', '--cfg-path', '/tmp/tmpkvjm_6pz']
[2025-07-07T00:00:12.973+0000] {standard_task_runner.py:85} INFO - Job 36: Subtask run_soda_scan
[2025-07-07T00:00:12.966+0000] {standard_task_runner.py:57} INFO - Started process 488 to run task
[2025-07-07T00:00:13.020+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-07T00:00:13.086+0000] {task_command.py:415} INFO - Running <TaskInstance: soda_scan_example.run_soda_scan scheduled__2025-07-06T00:00:00+00:00 [running]> on host 4010ea07c34f
[2025-07-07T00:00:13.199+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='soda_scan_example' AIRFLOW_CTX_TASK_ID='run_soda_scan' AIRFLOW_CTX_EXECUTION_DATE='2025-07-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-06T00:00:00+00:00'
[2025-07-07T00:00:13.204+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-07T00:00:13.205+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'export PATH=$PATH:/home/***/.local/bin && /home/***/.local/bin/soda scan -d local_postgres -c /usr/local/soda/config.yml /usr/local/soda/scan_checks.yml']
[2025-07-07T00:00:13.228+0000] {subprocess.py:86} INFO - Output:
[2025-07-07T00:00:14.337+0000] {subprocess.py:93} INFO - [00:00:14] Soda Core 3.5.5
[2025-07-07T00:00:14.418+0000] {subprocess.py:93} INFO - [00:00:14] Scan summary:
[2025-07-07T00:00:14.418+0000] {subprocess.py:93} INFO - [00:00:14] 4/4 checks PASSED:
[2025-07-07T00:00:14.419+0000] {subprocess.py:93} INFO - [00:00:14]     dag_run in local_postgres
[2025-07-07T00:00:14.419+0000] {subprocess.py:93} INFO - [00:00:14]       row_count > 0 [PASSED]
[2025-07-07T00:00:14.423+0000] {subprocess.py:93} INFO - [00:00:14]       missing_count(dag_id) = 0 [PASSED]
[2025-07-07T00:00:14.423+0000] {subprocess.py:93} INFO - [00:00:14]       missing_count(execution_date) = 0 [PASSED]
[2025-07-07T00:00:14.425+0000] {subprocess.py:93} INFO - [00:00:14]       duplicate_count(run_id) = 0 [PASSED]
[2025-07-07T00:00:14.426+0000] {subprocess.py:93} INFO - [00:00:14] All is good. No failures. No warnings. No errors.
[2025-07-07T00:00:14.933+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-07-07T00:00:14.955+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=soda_scan_example, task_id=run_soda_scan, execution_date=20250706T000000, start_date=20250707T000012, end_date=20250707T000014
[2025-07-07T00:00:14.988+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-07-07T00:00:15.007+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
